const_value = 1
	const NO_SAVE_EXISTS
	const SAVE_EXISTS
	const SAVE_CORRUPTED
	
AWARD_POINTS_LENGTH EQU 5
HIGH_SCORE_LENGTH EQU 6

NUM_MAIN_MENU_OPTIONS EQU 4

PRESS_START_Y EQU 112
PRESS_START_X EQU 52
	
POKEMON_TEXT_TILE_START EQU $24
TEXT_BOX_TOP_TILE_START EQU $43
TEAM_ROCKET_EDITION_TILE_START EQU $54
TITLE_SCREEN_SOLID_TILE_START EQU $7E
TITLE_SCREEN_MENU_LETTERS_TILE_START EQU $C0
MENU_BOX_TOP_TILE_START EQU $D0
TRE_TEXT_TILE_START EQU $E0
FONT_SYMBOLS_TILE_START EQU $E0
PRESS_START_TILE_START EQU $F2

const_value = -1
	const MOVE_MEOWTH_RIGHT
	const MOVE_EKANS_RIGHT
	const MOVE_EKANS_LEFT

ANIMATION_END EQU 80

; OPTION SCREEN

SPEED_Y     EQU 3
ANIMATION_Y EQU 8
STYLE_Y     EQU 13
CANCEL_Y    EQU 16

FAST_X      EQU 1
MEDIUM_X    EQU 7
SLOW_X      EQU 14

BATTLE_ANIMATION_F EQU 7
BATTLE_STYLE_F     EQU 6
CHALLENGE_MODE_F   EQU 5

; Text speed (frame delay between letters)
FAST_MASK          EQU 1
MEDIUM_MASK        EQU 3
SLOW_MASK          EQU 5

OPTION_ON       EQU 1
OPTION_OFF        EQU 10

DRAW_UPPER_RIGHT EQU 1
DRAW_CENTER EQU 0