; Tile Constants
TILE_FILTER_TEXT_START = $6C
TILE_FILTER_OFF_START = $6F
TILE_FILTER_ON_START = $71
TILE_TEXTBOX_BORDER_TOP = $73
TILE_ARROW_TILES_START = $74
TILE_TABS_START = $C0
TILE_TAB_BOTTOM_SOLID = $D4
TILE_TAB_BOTTOM_HIDDEN = $D8
TILE_CURSOR_START = $D9
TILE_EMPTY_RADIO = $EC
TILE_FILLED_RADIO = $F3
TILE_SELECT_START = $D5
TILE_DPAD = $78

; GFX Constants
GFX_TAB_WIDTH = 5
GFX_POCKETS_WIDTH = 8
GFX_POCKETS_HEIGHT = 9
GFX_CURSOR_SIZE = 4
GFX_FILTER_WIDTH = 3

; OAM Constants
OAM_CURSOR_X = $38
OAM_CURSOR_Y_START = $1C
OAM_TAB_TOP_Y = $10
OAM_TAB_BOTTOM_Y = $18

; Select Actions Constants
SELECT_ACTIONS_LENGTH = 4

; Inventory Data Constants
NUM_POCKETS = 4
POCKET_ATTRIBUTE_GFX = 0
POCKET_ATTRIBUTE_POSITION = 1
POCKET_ATTRIBUTE_ITEMS = 2
POCKET_ATTRIBUTE_SIZE = 3
POCKET_ATTRIBUTE_DATA_LENGTH = 7
INVENTORY_BUFFER_SIZE = 5

; Inventory Properties Constants
MASK_ACTIVE_POCKET = %00000011
MASK_CURSOR_POSITION = %00110000
BIT_INVENTORY_FILTER = 2
BIT_CURSOR_POSITION_LO = 4
BIT_CURSOR_POSITION_HI = 5

; Filter Masks, also double as bag type
FLAG_FIELD_USE = %00000001
FLAG_BATTLE_USE = %00000010
FLAG_SELLABLE = %00000100
FLAG_HOLDABLE = %00001000
FLAG_APPLY_TO_PK = %00010000

FILTER_START_MENU = FLAG_FIELD_USE
FILTER_BATTLE = FLAG_BATTLE_USE
FILTER_POKEMART = FLAG_SELLABLE
FILTER_PARTY_MENU = FLAG_HOLDABLE | FLAG_APPLY_TO_PK
