; Tile Constants
TILE_FILTER_TEXT_START = $6C
TILE_FILTER_OFF_START = $6F
TILE_FILTER_ON_START = $71
TILE_TEXTBOX_BORDER_TOP = $73
TILE_ARROW_TILES_START = $74
TILE_TABS_START = $C0
TILE_TAB_BOTTOM_SOLID = $D4
TILE_TAB_BOTTOM_HIDDEN = $D8
TILE_CURSOR_START = $D9
TILE_EMPTY_RADIO = $EC
TILE_FILLED_RADIO = $F3
TILE_SELECT_START = $D5
TILE_DPAD = $78

; GFX Constants
GFX_TAB_WIDTH = 5
GFX_POCKETS_WIDTH = 8
GFX_POCKETS_HEIGHT = 9
GFX_CURSOR_SIZE = 4
GFX_FILTER_WIDTH = 3

; OAM Constants
OAM_CURSOR_X = $38
OAM_CURSOR_Y_START = $1C
OAM_TAB_TOP_Y = $10
OAM_TAB_BOTTOM_Y = $18

; Select Actions Constants
SELECT_ACTIONS_LENGTH = 4

; Inventory Data Constants
NUM_POCKETS = 4
POCKET_ATTRIBUTE_GFX = 0
POCKET_ATTRIBUTE_POSITION = 1
POCKET_ATTRIBUTE_ITEMS = 2
POCKET_ATTRIBUTE_SIZE = 3
POCKET_ATTRIBUTE_DATA_LENGTH = 7
INVENTORY_BUFFER_SIZE = 5

; Item Data Constants
ITEM_DESCRIPTION = 0
ITEM_FILTER = 2
ITEM_ATTRIBUTE_DATA_SIZE = 3

; Inventory Properties Constants
MASK_ACTIVE_POCKET = %00000011
MASK_CURSOR_POSITION = %00110000
BIT_INVENTORY_FILTER = 2
BIT_CURSOR_POSITION_LO = 4
BIT_CURSOR_POSITION_HI = 5

; Filter Masks, also double as bag type
    const_def
    const BIT_FIELD_USE
    const BIT_BATTLE_USE
    const BIT_SELLABLE
    const BIT_HOLDABLE
    const BIT_APPLY_TO_PK
    const BIT_FIELD_QUICK_USE
    const BIT_BATTLE_QUICK_USE

FIELD_USE = 1 << BIT_FIELD_USE
BATTLE_USE = 1 << BIT_BATTLE_USE
SELLABLE = 1 << BIT_SELLABLE
HOLDABLE = 1 << BIT_HOLDABLE
APPLY_TO_PK = 1 << BIT_APPLY_TO_PK
FIELD_QUICK_USE = 1 << BIT_FIELD_QUICK_USE
BATTLE_QUICK_USE = 1 << BIT_BATTLE_QUICK_USE

STONE_USE = FIELD_USE | APPLY_TO_PK
QUICK_BATTLE_USE = BATTLE_QUICK_USE | BATTLE_USE
QUICK_FIELD_USE = FIELD_QUICK_USE | FIELD_USE

VITAMIN_USE = QUICK_FIELD_USE | APPLY_TO_PK | SELLABLE
HEALTH_USE = QUICK_BATTLE_USE | VITAMIN_USE


FILTER_FIELD = FIELD_USE
FILTER_BATTLE = BATTLE_USE
FILTER_POKEMART = SELLABLE
FILTER_PARTY_MENU = HOLDABLE | APPLY_TO_PK
