charmap "<pkmn>", $4A ; PkMn
charmap "@", $50
charmap "<PLAYER>", $52
charmap "<RIVAL>", $53
charmap "POKé", $54
charmap "<TARGET>", $59
charmap "<USER>", $5A

charmap "┌", $79
charmap "─", $7A
charmap "┐", $7B
charmap "│", $7C
charmap "└", $7D
charmap "┘", $7E

charmap " ", $7F
charmap "A", $80
charmap "B", $81
charmap "C", $82
charmap "D", $83
charmap "E", $84
charmap "F", $85
charmap "G", $86
charmap "H", $87
charmap "I", $88
charmap "J", $89
charmap "K", $8A
charmap "L", $8B
charmap "M", $8C
charmap "N", $8D
charmap "O", $8E
charmap "P", $8F
charmap "Q", $90
charmap "R", $91
charmap "S", $92
charmap "T", $93
charmap "U", $94
charmap "V", $95
charmap "W", $96
charmap "X", $97
charmap "Y", $98
charmap "Z", $99
charmap "(", $9A
charmap ")", $9B
charmap ":", $9C
charmap ";", $9D
charmap "[", $9E
charmap "]", $9F
charmap "a", $A0
charmap "b", $A1
charmap "c", $A2
charmap "d", $A3
charmap "e", $A4
charmap "f", $A5
charmap "g", $A6
charmap "h", $A7
charmap "i", $A8
charmap "j", $A9
charmap "k", $AA
charmap "l", $AB
charmap "m", $AC
charmap "n", $AD
charmap "o", $AE
charmap "p", $AF
charmap "q", $B0
charmap "r", $B1
charmap "s", $B2
charmap "t", $B3
charmap "u", $B4
charmap "v", $B5
charmap "w", $B6
charmap "x", $B7
charmap "y", $B8
charmap "z", $B9
charmap "é", $BA
charmap "'d", $BB
charmap "'l", $BC
charmap "'s", $BD
charmap "'t", $BE
charmap "'v", $BF

charmap "'", $E0
charmap "\"", $E1
charmap "฿", $E1
charmap "/", $E2
charmap "-", $E3
charmap "'r", $E4
charmap "'m", $E5
charmap "?", $E6
charmap "!", $E7
charmap ".", $E8
charmap "%", $E9
charmap "&", $EA
charmap "`", $EB
charmap "▷", $EC
charmap "▶", $ED
charmap "▲", $ED
charmap "▼", $EE
charmap "♂", $EF
charmap "$", $F0
charmap "#", $F1
charmap "*", $F2
charmap "+", $F3
charmap ",", $F4
charmap "♀", $F5
charmap "0", $F6
charmap "1", $F7
charmap "2", $F8
charmap "3", $F9
charmap "4", $FA
charmap "5", $FB
charmap "6", $FC
charmap "7", $FD
charmap "8", $FE
charmap "9", $FF
