Pokemon: MACRO
    ConvertName \1
    Prop Name, String, {NAME_STRING}
    Prop Front, Sprite
    Prop Back, Sprite
ENDM

    Table Pokemon
    Entry Bulbasaur
    Entry Ivysaur
    Entry Venusaur
    Entry Charmander
    Entry Charmeleon
    Entry Charizard
    Entry Squirtle
    Entry Wartortle
    Entry Blastoise
    Entry Caterpie
    Entry Metapod
    Entry Butterfree
    Entry Weedle
    Entry Kakuna
    Entry Beedrill
    Entry Pidgey
    Entry Pidgeotto
    Entry Pidgeot
    Entry Rattata
    Entry Raticate
    Entry Spearow
    Entry Fearow
    Entry Ekans
    Entry Arbok
    Entry Pikachu
    Entry Raichu
    Entry Sandshrew
    Entry Sandslash
    Entry Nidoran♀
    Entry Nidorina
    Entry Nidoqueen
    Entry Nidoran♂
    Entry Nidorino
    Entry Nidoking
    Entry Clefairy
    Entry Clefable
    Entry Vulpix
    Entry Ninetales
    Entry Jigglypuff
    Entry Wigglytuff
    Entry Zubat
    Entry Golbat
    Entry Oddish
    Entry Gloom
    Entry Vileplume
    Entry Paras
    Entry Parasect
    Entry Venonat
    Entry Venomoth
    Entry Diglett
    Entry Dugtrio
    Entry Meowth
    Entry Persian
    Entry Psyduck
    Entry Golduck
    Entry Mankey
    Entry Primeape
    Entry Growlithe
    Entry Arcanine
    Entry Poliwag
    Entry Poliwhirl
    Entry Poliwrath
    Entry Abra
    Entry Kadabra
    Entry Alakazam
    Entry Machop
    Entry Machoke
    Entry Machamp
    Entry Bellsprout
    Entry Weepinbell
    Entry Victreebel
    Entry Tentacool
    Entry Tentacruel
    Entry Geodude
    Entry Graveler
    Entry Golem
    Entry Ponyta
    Entry Rapidash
    Entry Slowpoke
    Entry Slowbro
    Entry Magnemite
    Entry Magneton
    Entry Farfetch'd
    Entry Doduo
    Entry Dodrio
    Entry Seel
    Entry Dewgong
    Entry Grimer
    Entry Muk
    Entry Shellder
    Entry Cloyster
    Entry Gastly
    Entry Haunter
    Entry Gengar
    Entry Onix
    Entry Drowzee
    Entry Hypno
    Entry Krabby
    Entry Kingler
    Entry Voltorb
    Entry Electrode
    Entry Exeggcute
    Entry Exeggutor
    Entry Cubone
    Entry Marowak
    Entry Hitmonlee
    Entry Hitmonchan
    Entry Lickitung
    Entry Koffing
    Entry Weezing
    Entry Rhyhorn
    Entry Rhydon
    Entry Chansey
    Entry Tangela
    Entry Kangaskhan
    Entry Horsea
    Entry Seadra
    Entry Goldeen
    Entry Seaking
    Entry Staryu
    Entry Starmie
    Entry Mr.Mime
    Entry Scyther
    Entry Jynx
    Entry Electabuzz
    Entry Magmar
    Entry Pinsir
    Entry Tauros
    Entry Magikarp
    Entry Gyarados
    Entry Lapras
    Entry Ditto
    Entry Eevee
    Entry Vaporeon
    Entry Jolteon
    Entry Flareon
    Entry Porygon
    Entry Omanyte
    Entry Omastar
    Entry Kabuto
    Entry Kabutops
    Entry Aerodactyl
    Entry Snorlax
    Entry Articuno
    Entry Zapdos
    Entry Moltres
    Entry Dratini
    Entry Dragonair
    Entry Dragonite
    Entry Mewtwo
    Entry Mew