    Pokemon Bulbasaur
    Pokemon Ivysaur
    Pokemon Venusaur
    Pokemon Charmander
    Pokemon Charmeleon
    Pokemon Charizard
    Pokemon Squirtle
    Pokemon Wartortle
    Pokemon Blastoise
    Pokemon Caterpie
    Pokemon Metapod
    Pokemon Butterfree
    Pokemon Weedle
    Pokemon Kakuna
    Pokemon Beedrill
    Pokemon Pidgey
    Pokemon Pidgeotto
    Pokemon Pidgeot
    Pokemon Rattata
    Pokemon Raticate
    Pokemon Spearow
    Pokemon Fearow
    Pokemon Ekans
    Pokemon Arbok
    Pokemon Pikachu
    Pokemon Raichu
    Pokemon Sandshrew
    Pokemon Sandslash
    Pokemon "Nidoran♀"
    Pokemon Nidorina
    Pokemon Nidoqueen
    Pokemon "Nidoran♂"
    Pokemon Nidorino
    Pokemon Nidoking
    Pokemon Clefairy
    Pokemon Clefable
    Pokemon Vulpix
    Pokemon Ninetales
    Pokemon Jigglypuff
    Pokemon Wigglytuff
    Pokemon Zubat
    Pokemon Golbat
    Pokemon Oddish
    Pokemon Gloom
    Pokemon Vileplume
    Pokemon Paras
    Pokemon Parasect
    Pokemon Venonat
    Pokemon Venomoth
    Pokemon Diglett
    Pokemon Dugtrio
    Pokemon Meowth
    Pokemon Persian
    Pokemon Psyduck
    Pokemon Golduck
    Pokemon Mankey
    Pokemon Primeape
    Pokemon Growlithe
    Pokemon Arcanine
    Pokemon Poliwag
    Pokemon Poliwhirl
    Pokemon Poliwrath
    Pokemon Abra
    Pokemon Kadabra
    Pokemon Alakazam
    Pokemon Machop
    Pokemon Machoke
    Pokemon Machamp
    Pokemon Bellsprout
    Pokemon Weepinbell
    Pokemon Victreebel
    Pokemon Tentacool
    Pokemon Tentacruel
    Pokemon Geodude
    Pokemon Graveler
    Pokemon Golem
    Pokemon Ponyta
    Pokemon Rapidash
    Pokemon Slowpoke
    Pokemon Slowbro
    Pokemon Magnemite
    Pokemon Magneton
    Pokemon "Farfetch'd"
    Pokemon Doduo
    Pokemon Dodrio
    Pokemon Seel
    Pokemon Dewgong
    Pokemon Grimer
    Pokemon Muk
    Pokemon Shellder
    Pokemon Cloyster
    Pokemon Gastly
    Pokemon Haunter
    Pokemon Gengar
    Pokemon Onix
    Pokemon Drowzee
    Pokemon Hypno
    Pokemon Krabby
    Pokemon Kingler
    Pokemon Voltorb
    Pokemon Electrode
    Pokemon Exeggcute
    Pokemon Exeggutor
    Pokemon Cubone
    Pokemon Marowak
    Pokemon Hitmonlee
    Pokemon Hitmonchan
    Pokemon Lickitung
    Pokemon Koffing
    Pokemon Weezing
    Pokemon Rhyhorn
    Pokemon Rhydon
    Pokemon Chansey
    Pokemon Tangela
    Pokemon Kangaskhan
    Pokemon Horsea
    Pokemon Seadra
    Pokemon Goldeen
    Pokemon Seaking
    Pokemon Staryu
    Pokemon Starmie
    Pokemon "Mr.Mime"
    Pokemon Scyther
    Pokemon Jynx
    Pokemon Electabuzz
    Pokemon Magmar
    Pokemon Pinsir
    Pokemon Tauros
    Pokemon Magikarp
    Pokemon Gyarados
    Pokemon Lapras
    Pokemon Ditto
    Pokemon Eevee
    Pokemon Vaporeon
    Pokemon Jolteon
    Pokemon Flareon
    Pokemon Porygon
    Pokemon Omanyte
    Pokemon Omastar
    Pokemon Kabuto
    Pokemon Kabutops
    Pokemon Aerodactyl
    Pokemon Snorlax
    Pokemon Articuno
    Pokemon Zapdos
    Pokemon Moltres
    Pokemon Dratini
    Pokemon Dragonair
    Pokemon Dragonite
    Pokemon Mewtwo
    Pokemon Mew