VermilionPokecenterScript:
	call Serial_TryEstablishingExternallyClockedConnection
	jp EnableAutoTextBoxDrawing

VermilionPokecenterTrainerHeader0:
	db TrainerHeaderTerminator

VermilionPokecenterTextPointers:
	dw VermilionHealNurseText
	dw VermilionPokecenterText2
	dw VermilionPokecenterText3
	dw VermilionTradeNurseText

VermilionHealNurseText:
	TX_POKECENTER_NURSE

VermilionPokecenterText2:
	fartext _VermilionPokecenterText2
	done

VermilionPokecenterText3:
	fartext _VermilionPokecenterText3
	done

VermilionTradeNurseText:
	TX_CABLE_CLUB_RECEPTIONIST
