ViridianForestEntranceScript:
	jp EnableAutoTextBoxDrawing

ViridianForestEntranceTextPointers:
	dw ViridianForestEntranceText1
	dw ViridianForestEntranceText2

ViridianForestEntranceText1:
	fartext _ViridianForestEntranceText1
	done

ViridianForestEntranceText2:
	fartext _ViridianForestEntranceText2
	done
