include "macros/Macros/macros.asm"

INCLUDE "macros/context_macros.asm"
INCLUDE "macros/type_macros.asm"
INCLUDE "macros/asm_macros.asm"
INCLUDE "macros/data_macros.asm"
INCLUDE "macros/text_macros.asm"
INCLUDE "macros/audio_macros.asm"
INCLUDE "macros/event_macros.asm"
INCLUDE "macros/table_macros.asm"
INCLUDE "macros/tiles_macros.asm"
INCLUDE "macros/map_object_macros.asm"
INCLUDE "macros/map_script_macros.asm"
INCLUDE "macros/script_macros.asm"
