    include "macros/Macros/debug.asm"
    include "macros/Macros/protos.asm"
    include "macros/Macros/base.asm"
    include "macros/Macros/library/context.asm"
    include "macros/Macros/library/types.asm"
    include "macros/Macros/library/definition.asm"
    include "macros/Macros/library/return.asm"
    ;Directory@import macros/Macros/library, structure, return
    include "macros/Macros/definitions/type.asm"
    include "macros/Macros/definitions/struct.asm"
    include "macros/Macros/definitions/scope.asm"
