ItemNames:
	str "MASTER BALL"
	str "ULTRA BALL"
	str "GREAT BALL"
	str "POKé BALL"
	str "TOWN MAP"
	str "BICYCLE"
	str "?????"
	str "SAFARI BALL"
	str "POKéDEX"
	str "MOON STONE"
	str "ANTIDOTE"
	str "BURN HEAL"
	str "ICE HEAL"
	str "AWAKENING"
	str "PARLYZ HEAL"
	str "FULL RESTORE"
	str "MAX POTION"
	str "HYPER POTION"
	str "SUPER POTION"
	str "POTION"
	str "BOULDERBADGE"
	str "CASCADEBADGE"
	str "THUNDERBADGE"
	str "RAINBOWBADGE"
	str "SOULBADGE"
	str "MARSHBADGE"
	str "VOLCANOBADGE"
	str "EARTHBADGE"
	str "ESCAPE ROPE"
	str "REPEL"
	str "OLD AMBER"
	str "FIRE STONE"
	str "THUNDERSTONE"
	str "WATER STONE"
	str "HP UP"
	str "PROTEIN"
	str "IRON"
	str "CARBOS"
	str "CALCIUM"
	str "RARE CANDY"
	str "DOME FOSSIL"
	str "HELIX FOSSIL"
	str "SECRET KEY"
	str "?????"
	str "BIKE VOUCHER"
	str "X ACCURACY"
	str "LEAF STONE"
	str "CARD KEY"
	str "NUGGET"
	str "PP UP"
	str "POKé DOLL"
	str "FULL HEAL"
	str "REVIVE"
	str "MAX REVIVE"
	str "GUARD SPEC."
	str "SUPER REPEL"
	str "MAX REPEL"
	str "DIRE HIT"
	str "COIN"
	str "FRESH WATER"
	str "SODA POP"
	str "LEMONADE"
	str "S.S.TICKET"
	str "GOLD TEETH"
	str "X ATTACK"
	str "X DEFEND"
	str "X SPEED"
	str "X SPECIAL"
	str "COIN CASE"
	str "OAK's PARCEL"
	str "ITEMFINDER"
	str "SILPH SCOPE"
	str "POKé FLUTE"
	str "LIFT KEY"
	str "EXP.ALL"
	str "OLD ROD"
	str "GOOD ROD"
	str "SUPER ROD"
	str "PP UP"
	str "ETHER"
	str "MAX ETHER"
	str "ELIXER"
	str "MAX ELIXER"
	str "B2F"
	str "B1F"
	str "1F"
	str "2F"
	str "3F"
	str "4F"
	str "5F"
	str "6F"
	str "7F"
	str "8F"
	str "9F"
	str "10F"
	str "11F"
	str "B4F"
