MoveNames::
	str "POUND"
	str "KARATE CHOP"
	str "DOUBLESLAP"
	str "COMET PUNCH"
	str "MEGA PUNCH"
	str "PAY DAY"
	str "FIRE PUNCH"
	str "ICE PUNCH"
	str "THUNDERPUNCH"
	str "SCRATCH"
	str "VICEGRIP"
	str "GUILLOTINE"
	str "RAZOR WIND"
	str "SWORDS DANCE"
	str "CUT"
	str "GUST"
	str "WING ATTACK"
	str "WHIRLWIND"
	str "FLY"
	str "BIND"
	str "SLAM"
	str "VINE WHIP"
	str "STOMP"
	str "DOUBLE KICK"
	str "MEGA KICK"
	str "JUMP KICK"
	str "ROLLING KICK"
	str "SAND-ATTACK"
	str "HEADBUTT"
	str "HORN ATTACK"
	str "FURY ATTACK"
	str "HORN DRILL"
	str "TACKLE"
	str "BODY SLAM"
	str "WRAP"
	str "TAKE DOWN"
	str "THRASH"
	str "DOUBLE-EDGE"
	str "TAIL WHIP"
	str "POISON STING"
	str "TWINEEDLE"
	str "PIN MISSILE"
	str "LEER"
	str "BITE"
	str "GROWL"
	str "ROAR"
	str "SING"
	str "SUPERSONIC"
	str "SONICBOOM"
	str "DISABLE"
	str "ACID"
	str "EMBER"
	str "FLAMETHROWER"
	str "MIST"
	str "WATER GUN"
	str "HYDRO PUMP"
	str "SURF"
	str "ICE BEAM"
	str "BLIZZARD"
	str "PSYBEAM"
	str "BUBBLEBEAM"
	str "AURORA BEAM"
	str "HYPER BEAM"
	str "PECK"
	str "DRILL PECK"
	str "SUBMISSION"
	str "LOW KICK"
	str "COUNTER"
	str "SEISMIC TOSS"
	str "STRENGTH"
	str "ABSORB"
	str "MEGA DRAIN"
	str "LEECH SEED"
	str "GROWTH"
	str "RAZOR LEAF"
	str "SOLARBEAM"
	str "POISONPOWDER"
	str "STUN SPORE"
	str "SLEEP POWDER"
	str "PETAL DANCE"
	str "STRING SHOT"
	str "DRAGON RAGE"
	str "FIRE SPIN"
	str "THUNDERSHOCK"
	str "THUNDERBOLT"
	str "THUNDER WAVE"
	str "THUNDER"
	str "ROCK THROW"
	str "EARTHQUAKE"
	str "FISSURE"
	str "DIG"
	str "TOXIC"
	str "CONFUSION"
	str "PSYCHIC"
	str "HYPNOSIS"
	str "MEDITATE"
	str "AGILITY"
	str "QUICK ATTACK"
	str "RAGE"
	str "TELEPORT"
	str "NIGHT SHADE"
	str "MIMIC"
	str "SCREECH"
	str "DOUBLE TEAM"
	str "RECOVER"
	str "HARDEN"
	str "MINIMIZE"
	str "SMOKESCREEN"
	str "CONFUSE RAY"
	str "WITHDRAW"
	str "DEFENSE CURL"
	str "BARRIER"
	str "LIGHT SCREEN"
	str "HAZE"
	str "REFLECT"
	str "FOCUS ENERGY"
	str "BIDE"
	str "METRONOME"
	str "MIRROR MOVE"
	str "SELFDESTRUCT"
	str "EGG BOMB"
	str "LICK"
	str "SMOG"
	str "SLUDGE"
	str "BONE CLUB"
	str "FIRE BLAST"
	str "WATERFALL"
	str "CLAMP"
	str "SWIFT"
	str "SKULL BASH"
	str "SPIKE CANNON"
	str "CONSTRICT"
	str "AMNESIA"
	str "KINESIS"
	str "SOFTBOILED"
	str "HI JUMP KICK"
	str "GLARE"
	str "DREAM EATER"
	str "POISON GAS"
	str "BARRAGE"
	str "LEECH LIFE"
	str "LOVELY KISS"
	str "SKY ATTACK"
	str "TRANSFORM"
	str "BUBBLE"
	str "DIZZY PUNCH"
	str "SPORE"
	str "FLASH"
	str "PSYWAVE"
	str "SPLASH"
	str "ACID ARMOR"
	str "CRABHAMMER"
	str "EXPLOSION"
	str "FURY SWIPES"
	str "BONEMERANG"
	str "REST"
	str "ROCK SLIDE"
	str "HYPER FANG"
	str "SHARPEN"
	str "CONVERSION"
	str "TRI ATTACK"
	str "SUPER FANG"
	str "SLASH"
	str "SUBSTITUTE"
	str "STRUGGLE"

