TrainerNames:
	str "YOUNGSTER"
	str "BUG CATCHER"
	str "LASS"
	str "SAILOR"
	str "JR.TRAINER♂"
	str "JR.TRAINER♀"
	str "POKéMANIAC"
	str "SUPER NERD"
	str "HIKER"
	str "BIKER"
	str "BURGLAR"
	str "ENGINEER"
	str "FISHERMAN"
	str "SWIMMER"
	str "CUE BALL"
	str "GAMBLER"
	str "BEAUTY"
	str "PSYCHIC"
	str "ROCKER"
	str "JUGGLER"
	str "TAMER"
	str "BIRD KEEPER"
	str "BLACKBELT"
	str "RIVAL1"
	str "PROF.OAK"
	str "SCIENTIST"
	str "GIOVANNI"
	str "ROCKET"
	str "COOLTRAINER♂"
	str "COOLTRAINER♀"
	str "BRUNO"
	str "BROCK"
	str "MISTY"
	str "LT.SURGE"
	str "ERIKA"
	str "KOGA"
	str "BLAINE"
	str "SABRINA"
	str "GENTLEMAN"
	str "RIVAL2"
	str "RIVAL3"
	str "LORELEI"
	str "CHANNELER"
	str "AGATHA"
	str "LANCE"
