; Viridian Forest
db 6,WEEDLE,CATERPIE,0
db 7,WEEDLE,KAKUNA,WEEDLE,0
db 9,WEEDLE,0
; Route 3
db 10,CATERPIE,WEEDLE,CATERPIE,0
db 9,WEEDLE,KAKUNA,CATERPIE,METAPOD,0
db 11,CATERPIE,METAPOD,0
; Mt. Moon 1F
db 11,WEEDLE,KAKUNA,0
db 10,CATERPIE,METAPOD,CATERPIE,0
; Route 24
db 14,CATERPIE,WEEDLE,0
; Route 6
db 16,WEEDLE,CATERPIE,WEEDLE,0
db 20,BUTTERFREE,0
; Unused
db 18,METAPOD,CATERPIE,VENONAT,0
; Route 9
db 19,BEEDRILL,BEEDRILL,0
db 20,CATERPIE,WEEDLE,VENONAT,0