; Celadon Gym
db 24,WEEPINBELL,GLOOM,IVYSAUR,0
; Victory Road 3F
db 43,BELLSPROUT,WEEPINBELL,VICTREEBEL,0
db 43,PARASECT,DEWGONG,CHANSEY,0
; Unused
db 46,VILEPLUME,BUTTERFREE,0
; Victory Road 1F
db 44,PERSIAN,NINETALES,0
; Unused
db 45,IVYSAUR,VENUSAUR,0
db 45,NIDORINA,NIDOQUEEN,0
db 43,PERSIAN,NINETALES,RAICHU,0