; Viridian Gym
db 39,NIDORINO,NIDOKING,0
; Victory Road 3F
db 43,EXEGGUTOR,CLOYSTER,ARCANINE,0
db 43,KINGLER,TENTACRUEL,BLASTOISE,0
; Unused
db 45,KINGLER,STARMIE,0
; Victory Road 1F
db 42,IVYSAUR,WARTORTLE,CHARMELEON,CHARIZARD,0
; Unused
db 44,IVYSAUR,WARTORTLE,CHARMELEON,0
db 49,NIDOKING,0
db 44,KINGLER,CLOYSTER,0
; Viridian Gym
db 39,SANDSLASH,DUGTRIO,0
db 43,RHYHORN,0