; SS Anne 2F Rooms
db 17,GOLDEEN,TENTACOOL,GOLDEEN,0
; SS Anne B1F Rooms
db 17,TENTACOOL,STARYU,SHELLDER,0
; Route 12
db 22,GOLDEEN,POLIWAG,GOLDEEN,0
db 24,TENTACOOL,GOLDEEN,0
db 27,GOLDEEN,0
db 21,POLIWAG,SHELLDER,GOLDEEN,HORSEA,0
; Route 21
db 28,SEAKING,GOLDEEN,SEAKING,SEAKING,0
db 31,SHELLDER,CLOYSTER,0
db 27,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,MAGIKARP,0
db 33,SEAKING,GOLDEEN,0
; Route 12
db 24,MAGIKARP,MAGIKARP,0