; Mt. Moon B2F
db 13,RATTATA,ZUBAT,0
db 11,SANDSHREW,RATTATA,ZUBAT,0
db 12,ZUBAT,EKANS,0
db 16,RATICATE,0
; Cerulean City
db 17,MACHOP,DROWZEE,0
; Route 24
db 15,EKANS,ZUBAT,0
; Game Corner
db 20,RATICATE,ZUBAT,0
; Rocket Hideout B1F
db 21,DROWZEE,MACHOP,0
db 21,RATICATE,RATICATE,0
db 20,GRIMER,KOFFING,KOFFING,0
db 19,RATTATA,RATICATE,RATICATE,RATTATA,0
db 22,GRIMER,KOFFING,0
; Rocket Hideout B2F
db 17,ZUBAT,KOFFING,GRIMER,ZUBAT,RATICATE,0
; Rocket Hideout B3F
db 20,RATTATA,RATICATE,DROWZEE,0
db 21,MACHOP,MACHOP,0
; Rocket Hideout B4F
db 23,SANDSHREW,EKANS,SANDSLASH,0
db 23,EKANS,SANDSHREW,ARBOK,0
db 21,KOFFING,ZUBAT,0
; Pokémon Tower 7F
db 25,ZUBAT,ZUBAT,GOLBAT,0
db 26,KOFFING,DROWZEE,0
db 23,ZUBAT,RATTATA,RATICATE,ZUBAT,0
; Unused
db 26,DROWZEE,KOFFING,0
; Silph Co. 2F
db 29,CUBONE,ZUBAT,0
db 25,GOLBAT,ZUBAT,ZUBAT,RATICATE,ZUBAT,0
; Silph Co. 3F
db 28,RATICATE,HYPNO,RATICATE,0
; Silph Co. 4F
db 29,MACHOP,DROWZEE,0
db 28,EKANS,ZUBAT,CUBONE,0
; Silph Co. 5F
db 33,ARBOK,0
db 33,HYPNO,0
; Silph Co. 6F
db 29,MACHOP,MACHOKE,0
db 28,ZUBAT,ZUBAT,GOLBAT,0
; Silph Co. 7F
db 26,RATICATE,ARBOK,KOFFING,GOLBAT,0
db 29,CUBONE,CUBONE,0
db 29,SANDSHREW,SANDSLASH,0
; Silph Co. 8F
db 26,RATICATE,ZUBAT,GOLBAT,RATTATA,0
db 28,WEEZING,GOLBAT,KOFFING,0
; Silph Co. 9F
db 28,DROWZEE,GRIMER,MACHOP,0
db 28,GOLBAT,DROWZEE,HYPNO,0
; Silph Co. 10F
db 33,MACHOKE,0
; Silph Co. 11F
db 25,RATTATA,RATTATA,ZUBAT,RATTATA,EKANS,0
db 32,CUBONE,DROWZEE,MAROWAK,0