; Unused
db 34,KOFFING,VOLTORB,0
; Silph Co. 2F
db 26,GRIMER,WEEZING,KOFFING,WEEZING,0
db 28,MAGNEMITE,VOLTORB,MAGNETON,0
; Silph Co. 3F/Mansion 1F
db 29,ELECTRODE,WEEZING,0
; Silph Co. 4F
db 33,ELECTRODE,0
; Silph Co. 5F
db 26,MAGNETON,KOFFING,WEEZING,MAGNEMITE,0
; Silph Co. 6F
db 25,VOLTORB,KOFFING,MAGNETON,MAGNEMITE,KOFFING,0
; Silph Co. 7F
db 29,ELECTRODE,MUK,0
; Silph Co. 8F
db 29,GRIMER,ELECTRODE,0
; Silph Co. 9F
db 28,VOLTORB,KOFFING,MAGNETON,0
; Silph Co. 10F
db 29,MAGNEMITE,KOFFING,0
; Mansion 3F
db 33,MAGNEMITE,MAGNETON,VOLTORB,0
; Mansion B1F
db 34,MAGNEMITE,ELECTRODE,0