; Fuchsia Gym
db 34,SANDSLASH,ARBOK,0
db 33,ARBOK,SANDSLASH,ARBOK,0
; Viridian Gym
db 43,RHYHORN,0
db 39,ARBOK,TAUROS,0
; Victory Road 2F
db 44,PERSIAN,GOLDUCK,0
; Unused
db 42,RHYHORN,PRIMEAPE,ARBOK,TAUROS,0